services:
  producer:
    build:
      context: ./docker/producer
    container_name: producer
    restart: on-failure
    healthcheck:
      test: [ "CMD", "pgrap", "-f", "producer.py" ]
      interval: 5m
      timeout: 5s
      retries: 5
      start_period: 30s
  consumer:
    build:
      context: ./docker/consumer
    container_name: consumer
    restart: on-failure
    healthcheck:
      test: [ "CMD", "pgrep", "-f", "consumer.py" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  minio:
    build:
      context: ./docker/storage/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  minio-client:
    build:
      context: ./docker/storage/minio-client
    container_name: minio-client
    depends_on:
      - minio
    restart: on-failure
    healthcheck:
      test: [ "CMD", "mc", "ls", "local" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  prometheus:
    build:
      context: ./docker/monitor/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  grafana:
    build:
      context: ./docker/monitor/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
volumes:
  minio-data:
